### ISSUE TITLE
Indicate that `$intercom` is required somewhere

### ISSUE THREAD

**Issue by ScopeyNZ** [dogchef-be/nuxt-intercom#1]
Hi there. Thanks for this module.

I was having issues getting the intercom button to show up as the 2 step getting started guide doesn't mention the fact that `$intercom()` is required at least once for the intercom scripts to load. I think this should be mentioned somewhere to save others the time of figuring it out.

Happy to submit a PR, but I wasn't sure what the recommended approach should be. In the end - we just put it in a `mounted` call on our layout component.

**Comment by fabiofdsantos** [comment]
@ScopeyNZ, thanks for opening the issue!

The module was created (mainly) to avoid loading Intercom everywhere. We can add an option for auto-loading on page load.

**Comment by ScopeyNZ** [comment]
Thanks Fábio. We do appreciate the "only load when required" feature, as we've only enabled it for one layout (of several) - just noting it wasn't so clear how to get it to show initially.

**Comment by rishabhONJUNO** [comment]
Hey, Can you add One deployed example for this, would be a great help?

**Comment by fabiofdsantos** [comment]
@rishabhONJUNO, you just need to follow the [Setup](https://github.com/dogchef-be/nuxt-intercom#setup) and [Usage](https://github.com/dogchef-be/nuxt-intercom#usage) instructions.

**Comment by rishabhONJUNO** [comment]
> @rishabhONJUNO, you just need to follow the [Setup](https://github.com/dogchef-be/nuxt-intercom#setup) and [Usage](https://github.com/dogchef-be/nuxt-intercom#usage) instructions.

Actually, I followed the steps but it's not working.
 - How to load intercom?
 - How to use it in pages?

**Comment by fabiofdsantos** [comment]
> > @rishabhONJUNO, you just need to follow the [Setup](https://github.com/dogchef-be/nuxt-intercom#setup) and [Usage](https://github.com/dogchef-be/nuxt-intercom#usage) instructions.
> 
> Actually, I followed the steps but it's not working.
> 
> * How to load intercom?
> * How to use it in pages?

You should include `this.$intercom()` in `created()` method.

Currently, Intercom is loaded only when required. The next version will include an option to load it in every page.

**Comment by fabiofdsantos** [comment]
> > @rishabhONJUNO, you just need to follow the [Setup](https://github.com/dogchef-be/nuxt-intercom#setup) and [Usage](https://github.com/dogchef-be/nuxt-intercom#usage) instructions.
> 
> Actually, I followed the steps but it's not working.
> 
> * How to load intercom?
> * How to use it in pages?

You should include `this.$intercom()` in `created()` method. For example:
```
this.$intercom('update', { hide_default_launcher: true })
```
The above code will load Intercom (if it was not loaded before) and execute the `update` command.

Currently, Intercom is loaded only when required. The next version will include an option to load it in every page.

**Comment by CHEWX** [comment]
Hey @fabiofdsantos ,

Any update on the next version, as adding the `init` in `created()` method for every layout isn't ideal.

Also, when you do, the default launcher icon doesn't display? 

Thanks

**Comment by fabiofdsantos** [comment]
@CHEWX 

Intercom is initialised on the first usage. For example `$intercom('show')`, `$intercom('update', {...})`, etc.

I can work on the option to load it in every page during the next month. Otherwise feel free to submit a pull request 👍🏻

**Comment by CHEWX** [comment]
Thanks for the quick reply.

No problem on the load of every page option.

The methods above work, however, the icons still won't show, it's an empty div. It looks like you have to use a custom icon/trigger as per your https://github.com/dogchef-be/nuxt-intercom#usage section, rather than using the core trigger which make `hideDefaultLauncher` redundant?

(![Screenshot 2021-07-28 at 14 59 59](https://user-images.githubusercontent.com/5207147/127338969-6b7ddce4-8fd2-4144-a4a3-8a7aba620035.jpg))

**Comment by CHEWX** [comment]
Scrap that, it's loaded it now, strange.

**Comment by fabiofdsantos** [comment]
You're free to use a custom trigger or the default one. For example, we are using a custom one for mobile devices in order to avoid potential conflicts with other elements.

**Comment by fabiofdsantos** [comment]
Issue #3 has been created for loading Intercom in every page (automatically).
